tasks:
  - init: echo "Installing and configuring Deno..."
    command: alias deno="/home/gitpod/.deno/bin/deno" && echo "Check if it worked with deno --version!"
    
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - justjavac.vscode-deno@1.33.0:isaDa2L7SOsJRLd8z5N0sQ==